### PR TITLE
Minimal changes for critter profiling

### PR DESCRIPTION
**Pull request by huttered40**
I incorporated minimal changes to get CTF to build with critter. The user can profile CTF code using critter by specifying the correct configure command.

I successfully built CTF using 3 configure commands on Stampede2:
1) CTF + Critter - `./configure '--no-dynamic' 'LIB_PATH=-L/home1/05608/tg849075/critter/lib -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/' 'LIBS=-lcritter -lmkl_scalapack_lp64 -Wl,--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_lp64 -Wl,--end-group -lpthread -lm' 'CXXFLAGS=-O3 -DCRITTER' 'INCLUDES=-I/home1/05608/tg849075/critter/src/'`
2) CTF with no profiling - `./configure '--no-dynamic' 'LIB_PATH=-L/home1/05608/tg849075/critter/lib -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/' 'LIBS=-lcritter -lmkl_scalapack_lp64 -Wl,--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_lp64 -Wl,--end-group -lpthread -lm' 'CXXFLAGS=-O3' 'INCLUDES=-I/home1/05608/tg849075/critter/src/'`
3) CTF + TAU/PMPI`./configure '--no-dynamic' 'LIB_PATH=-L/home1/05608/tg849075/critter/lib -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/' 'LIBS=-lcritter -lmkl_scalapack_lp64 -Wl,--start-group -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_lp64 -Wl,--end-group -lpthread -lm' 'CXXFLAGS=-O3 -DPROFILE -DPMPI' 'INCLUDES=-I/home1/05608/tg849075/critter/src/'`

One might also consider adding a check in the configure file to prevent user from specifying both PROFILE and CRITTER, and PMPI and CRITTER. Also, although critter is an external library, I opted against creating its own `--with-critter` tag in the configure script to avoid messing with the code in the configure file. I think its simplest to just built critter on one's own, and have the 3 profiling tags {PMPI, PROFILE, CRITTER} be specifiable in the exact same way.

### CODE REVIEW

**Comment by solomonik** [comment]
Thanks, this looks good. But why the change to contraction.cxx with calc_frac? That looks related to an unrelated recent commit, so I guess perhaps a result of some merge, but want to check.

**Comment by solomonik** [comment]
I also had in mind calling critter start() and stop() from src/interface/world.cxx, specifically calling start in initialize() and calling stop in the destructor of the global world (line 109). Do you think this is inadvisable?

**Comment by huttered40** [comment]
> Thanks, this looks good. But why the change to contraction.cxx with calc_frac? That looks related to an unrelated recent commit, so I guess perhaps a result of some merge, but want to check.

The modifications in that file must have crept in there from some other merge. I had to comment out the redefinition of the nnz variables, because they were already defined. After looking at the current CTF master source code, I think the changes in that file can be discarded altogether.

**Comment by huttered40** [comment]
> I also had in mind calling critter start() and stop() from src/interface/world.cxx, specifically calling start in initialize() and calling stop in the destructor of the global world (line 109). Do you think this is inadvisable?

I'd have to test this. Gut instinct tells me this would disallow the user to call critter::start() and critter::stop() from their application code, but yes I agree its even less invasive. Let me experiment with that. For this to work, critter would have to recognize cases where its supposed to save the state of its profiling data so that multiple start() and stop() pairs can be appended together essentially. I have seen a few application codes that use CTF but also use MPI separately.

**Comment by solomonik** [comment]
@huttered40 perhaps what CTF does with timer epochs is one model for nested critter start/stop. For CTF could also provide a is_started(), so that CTF only starts when the user has not already started it and stops later only it if it had started it

**Comment by huttered40** [comment]
> @huttered40 perhaps what CTF does with timer epochs is one model for nested critter start/stop. For CTF could also provide a is_started(), so that CTF only starts when the user has not already started it and stops later only it if it had started it

Right, I thought something like that as soon as I typed my reply. Perhaps it also makes sense to try a python CTF code running on Stampede2 as well before this gets merged in?

**Comment by solomonik** [comment]
Will merge this PR, since it enables use of critter for C++ apps with CTF, which we need now. The automatic start would indeed be useful for extension to python and we can test that then.

**Pull request merged**
